In [3]:
# Loading requirements
from core.lib.pyRequirment import *

In [6]:
a = np.random.rand(2, 2, 3)
a

array([[[0.80708897, 0.58462788, 0.04044255],
        [0.22161788, 0.35523448, 0.70349252]],

       [[0.90452008, 0.06071953, 0.4487196 ],
        [0.17981608, 0.43394683, 0.31495312]]])

In [11]:
b = a.transpose(2,1,0)
b.flatten()

array([0.80708897, 0.90452008, 0.22161788, 0.17981608, 0.58462788,
       0.06071953, 0.35523448, 0.43394683, 0.04044255, 0.4487196 ,
       0.70349252, 0.31495312])

In [14]:
range(0, 5, 2)

range(0, 5, 2)

In [34]:
a = np.random.rand(8,2)

In [28]:
a

array([0.46767765, 0.65556779, 0.75564677, 0.51188859, 0.01716808,
       0.39660814, 0.25848193, 0.92185097])

In [30]:
a[0:2] = 0

In [38]:
a = np.array([[1, 2, 5, 6, 2, 2], [6, 7, 4, 3, 7, 1]])
a

array([[1, 2, 5, 6, 2, 2],
       [6, 7, 4, 3, 7, 1]])

In [40]:
np.unique(a, axis=1)

array([[1, 2, 2, 5, 6],
       [6, 1, 7, 4, 3]])

In [41]:
np.zeros(6, dtype=np.int16)

array([0, 0, 0, 0, 0, 0], dtype=int16)

In [48]:
_, x = np.unique(np.array([1,2,3,4,2,1,6]), return_index=True)

In [51]:
pp = 1 if 1 else 0
pp

1